name: R Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install dependencies
        run: |
          Rscript -e "install.packages('googledrive')"
          Rscript -e "install.packages('gargle')"
          Rscript -e "install.packages('httr')"

      - name: Decrypt .secrets
        env:
          GDRIVE_AUTH: ${{ secrets.AVT_DRIVE }}
        run: |
          echo "${AVT_DRIVE}" > .secrets
         # gpg --quiet --batch --yes --decrypt --passphrase="$AVT_DRIVE" --output .secrets .secrets.gpg

      - name: Authenticate with Google Drive
        run: |
          Rscript -e "library(googledrive); drive_auth(cache = '.secrets', email = 'abreefpilz@gmail.com')"
